### ISSUE TITLE
doge search

### ISSUE THREAD

**Issue by 0xhex** [talentlessguy/balance-crypto#2]
Hello, i am searching doge coin with this : 

balance('0xf8e9b725e0de8a9546916861c2904b0eb8805b96', 'DOGE', {
  keys: {
    etherscan: process.env.ETHERSCAN_KEY,
    blockcypher: process.env.BLOCKYCPHER_KEY
  },
  verbose: true
}).then((res) => console.log(res))

it says every doge address : Error: Invalid address "0xf8e9b725e0de8a9546916861c2904b0eb8805b96" for DOGE

**Comment by talentlessguy** [comment]
are you sure those are doge addresses? `0x` is more of an ethereum thing

this is the regex I use for DOGE

https://github.com/talentlessguy/balance-crypto/blob/55e60f73cd89e4dd48e6a015b060e647e4585735/src/services/blockcypher.js#L1-L20

and it works for such address: `DBXu2kgc3xtvCUWFcxFE3r9hEYgmuaaCyD`

or it's some other DOGE? maybe an ethereum-wrapped DOGE?

**Comment by talentlessguy** [comment]
closing as invalid, it's an ethereum address, not DOGE

https://etherscan.io/address/0xf8e9b725e0de8a9546916861c2904b0eb8805b96
